name: coffea-env
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - awkward>=2.5.0
  - ipython
  - root
  - sklearn
  - numba
  - htcondor
  - dask
  - dask-awkward
  - dask-histogram
  - dask-jobqueue
  - distributed
  - ndcctools
  - dill
  - pyarrow
  - xrootd
  - pyyaml
  - ipywidgets
  - pip:
    - coffea>=2023.10.0rc1