name: triphoton-env
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - coffea
  - root
  - numba
  - htcondor
  - dask
  - dask-awkward
  - dask-histogram
  - dask-jobqueue
  - distributed
  - ndcctools
  - dill
  - pyarrow
  - xrootd
  - pyyaml
  - ipywidgets
  - ipython